# C:\Users\z33ya\AppData\Roaming\alacritty\themes\themes
import = [
	"C:\\Users\\z33ya\\AppData\\Roaming\\alacritty\\themes\\themes\\argonaut.toml"
]

[shell]
program = "C:\\Windows\\System32\\wsl.exe -d Ubuntu"
args = ["--cd ~"]

[env]
TERM = "xterm-256color"


[window]
title = "💻"
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12
